# Generated by Django 6.0.2 on 2026-02-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContextCore', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
